### ISSUE TITLE
need hard refactor

### ISSUE THREAD

**Issue by blackhammer-dev** [Bitvested/ta.py#3]
Hello
Your library is great but very hard to use. Please refractor it to make it usable
Receive fixed dataFream as input
The indicator finds its value
Meaningful output in dictionaries 

Please take a look at this library and you will notice its ease of use
https://github.com/peerchemist/finta

**Comment by Vultwo** [comment]
Hi, I am not planning to add features like pandas dataframes to this library, sorry.
It shouldn't be that hard to implement features like dataframes from your end.
