### ISSUE TITLE
Heikin ashi and supertrend functionality returning duplicate values | 27-Aug-2022

### ISSUE THREAD

**Issue by pratiknc22793** [Bitvested/ta.py#8]
Supertrend is returning duplicate values while processing a stock's OHLC (open, high, low, close) data.
Have attached unprocessed OHLC data **df.csv** file below.
First: I am processing this OHLC csv data frame to Heikin Ashi candle data using **ta.ha** from pandas_ta
Then: I am processing this Heikin Ashi processed data with **ta.supertrend** from pandas_ta.

In both pandas_ta methods, I am getting duplicate values.
Though SuperTrend signal is provided accurately. Values are duplicate.

**Unprocessed CSV FILE -**  [df.csv](https://github.com/Bitvested/ta.py/files/9438125/df.csv)

![image](https://user-images.githubusercontent.com/29261039/187034588-35a9c705-1f36-40d9-9b44-b25e30ad42b4.png)

**Comment by Vultwo** [comment]
I'm not sure if this is a bug or not.
Sometimes the supertrend value stays the same, it's a property of the indicator.
Can you verify that the duplicate values are actually wrong when compared to other libraries?

**Comment by pratiknc22793** [comment]
Will check and revert.
If those values are of range, then what you said might be true.
Thanks

**Comment by Vultwo** [comment]
No problem,
Let me know if you encounter any other issues.
