### ISSUE TITLE
ta.fibbands

### ISSUE THREAD

**Issue by pavelxx1** [Bitvested/ta.py#9]
Hi
Can't understand how to plot corectly with price
```
input:
highlow_data = [[19963.24, 20009.0], [19975.0, 20018.5], [19995.62, 20046.32], [19982.15, 20029.52], [19983.7, 20001.22]]
close_data = [19990.16, 19997.24, 20028.58, 19988.03, 20000.71]

length = 4
deviations = 3
x=ta.fibbands(highlow_data , length, deviations)
plt.plot(x)
plt.plot(close_data)

```
plot result bad. thx

**Comment by Vultwo** [comment]
Hi,

I think the problem is that your lengths are not the same?
Your x and close_data variables should probably be the same length.

If this is not the issue, could you post the output of the function?

**Comment by pavelxx1** [comment]
yep, my mistake) closed
